import { readFile, rm } from 'node:fs/promises';

import { describe, expect, test } from 'bun:test';

const exampleRoot = new URL('../examples/file-routing-basic/', import.meta.url);
const generatedDir = new URL('./.potentia/', exampleRoot);
const generatedFile = new URL('./.potentia/routes.generated.js', exampleRoot);

describe('file routing basic example', () => {
  test('generates routes and serves the example app', async () => {
    await cleanup();

    try {
      const { generate } = await import(`../examples/file-routing-basic/generate.js?cache=${Date.now()}`);
      const result = await generate();

      expect(result.ok).toBe(true);
      expect(result.routes).toBe(3);
      expect(result.scopes).toBe(1);
      expect(result.diagnostics).toEqual([]);

      const source = await readFile(generatedFile, 'utf8');
      expect(source).toStartWith('// Generated by PotentiaJS. Do not edit by hand.');
      expect(source).toContain("import { createRoutes, mount } from '@potentiajs/core';");
      expect(source).toContain("import route0 from '../routes/index.js';");
      expect(source).toContain("import route1 from '../routes/health.js';");
      expect(source).not.toContain('node:fs');

      const { app } = await import(`../examples/file-routing-basic/app.js?cache=${Date.now()}`);

      const home = await app.fetch(new Request('http://localhost/'));
      expect(home.status).toBe(200);
      expect(await home.text()).toBe('file routing home');

      const health = await app.fetch(new Request('http://localhost/health'));
      expect(health.status).toBe(200);
      expect(await health.json()).toEqual({ ok: true });

      const user = await app.fetch(new Request('http://localhost/users/ada'));
      expect(user.status).toBe(200);
      expect(user.headers.get('x-file-routing-scope')).toBe('users');
      expect(user.headers.get('x-file-routing-path')).toBe('/users/ada');
      expect(await user.json()).toEqual({
        id: 'ada',
        from: 'file-routing-basic'
      });
    } finally {
      await cleanup();
    }
  });
});

async function cleanup() {
  await rm(generatedDir, { recursive: true, force: true });
}
