import { mkdir, rm, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

import { describe, expect, test } from 'bun:test';

import * as rootApi from '@potentiajs/core';
import * as fileRoutingApi from '@potentiajs/core/file-routing';

const fixtureRoot = new URL('./fixtures/file-routing-subpath-export/', import.meta.url).pathname;
const routesRoot = resolve(fixtureRoot, 'routes');
const outputFile = resolve(fixtureRoot, '.potentia/routes.generated.js');

describe('file routing public subpath export', () => {
  test('subpath exposes only generateFileRoutes', () => {
    expect(Object.keys(fileRoutingApi).sort()).toEqual(['generateFileRoutes']);
    expect(typeof fileRoutingApi.generateFileRoutes).toBe('function');
  });

  test('root package does not export generateFileRoutes', () => {
    expect('generateFileRoutes' in rootApi).toBe(false);
  });

  test('subpath can generate output with package default', async () => {
    await setupRoutes();

    try {
      const result = await fileRoutingApi.generateFileRoutes({ rootDir: routesRoot, outputFile });

      expect(result.ok).toBe(true);
      expect(result.source).toContain("import { createRoutes, mount } from '@potentiajs/core';");
      expect(result.source).toStartWith('// Generated by PotentiaJS. Do not edit by hand.');
      expect(result.source).not.toContain('node:fs');
    } finally {
      await cleanup();
    }
  });
});

async function setupRoutes() {
  await cleanup();
  await mkdir(routesRoot, { recursive: true });
  await writeFile(resolve(routesRoot, 'index.js'), [
    "import { route, text, ok } from '@potentiajs/core';",
    "export default route('GET', '/', () => ok(text('home')));",
    ''
  ].join('\n'));
}

async function cleanup() {
  await rm(fixtureRoot, { recursive: true, force: true });
}
