import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';

import { describe, expect, test } from 'bun:test';

import packageJson from '../package.json' with { type: 'json' };
import { checkFileRoutes, createJsonEnvelope, main, parseArgs, toJsonDiagnostics, USAGE } from '../src/cli.js';
import * as rootApi from '../src/index.js';
import * as fileRoutingApi from '../src/file-routing.js';

const fixtureRoot = new URL('./fixtures/file-routing-cli/', import.meta.url).pathname;

describe('file routing CLI parser', () => {
  test('parses default routes generate command', () => {
    expect(parseArgs(['routes', 'generate'])).toEqual({
      ok: true,
      command: 'routes generate',
      options: {
        root: 'routes',
        out: '.potentia/routes.generated.js',
        packageName: '@potentiajs/core',
        cwd: null,
        json: false
      }
    });
  });

  test('parses default routes check command', () => {
    expect(parseArgs(['routes', 'check'])).toEqual({
      ok: true,
      command: 'routes check',
      options: {
        root: 'routes',
        out: '.potentia/routes.generated.js',
        packageName: '@potentiajs/core',
        cwd: null,
        json: false
      }
    });
  });

  test('parses routes generate command with all flags', () => {
    expect(parseArgs([
      'routes',
      'generate',
      '--root',
      'app/routes',
      '--out',
      'generated/routes.js',
      '--package',
      '@example/core',
      '--cwd',
      'examples/app'
    ])).toEqual({
      ok: true,
      command: 'routes generate',
      options: {
        root: 'app/routes',
        out: 'generated/routes.js',
        packageName: '@example/core',
        cwd: 'examples/app',
        json: false
      }
    });
  });

  test('parses routes check command with all flags', () => {
    expect(parseArgs([
      'routes',
      'check',
      '--root',
      'app/routes',
      '--out',
      'generated/routes.js',
      '--package',
      '@example/core',
      '--cwd',
      'examples/app'
    ])).toEqual({
      ok: true,
      command: 'routes check',
      options: {
        root: 'app/routes',
        out: 'generated/routes.js',
        packageName: '@example/core',
        cwd: 'examples/app',
        json: false
      }
    });
  });

  test('parses --json for generate and check', () => {
    expect(parseArgs(['routes', 'generate', '--json'])).toEqual({
      ok: true,
      command: 'routes generate',
      options: {
        root: 'routes',
        out: '.potentia/routes.generated.js',
        packageName: '@potentiajs/core',
        cwd: null,
        json: true
      }
    });

    expect(parseArgs(['routes', 'check', '--json', '--root', 'app/routes'])).toEqual({
      ok: true,
      command: 'routes check',
      options: {
        root: 'app/routes',
        out: '.potentia/routes.generated.js',
        packageName: '@potentiajs/core',
        cwd: null,
        json: true
      }
    });
  });

  test('rejects invalid usage deterministically', () => {
    const invalid = [
      [],
      ['routes'],
      ['routes', 'unknown'],
      ['routes', 'generate', '--unknown'],
      ['routes', 'generate', '--root'],
      ['routes', 'generate', '--root', '--out'],
      ['routes', 'generate', '--check'],
      ['routes', 'generate', '--check', '--json'],
      ['routes', 'check', '--watch'],
      ['routes', 'check', '--config'],
      ['routes', 'check', '--watch', '--json'],
      ['routes', 'check', '--config', '--json'],
      ['routes', 'check', 'extra'],
      ['dev'],
      ['build']
    ];

    for (const args of invalid) {
      const parsed = parseArgs(args);
      expect(parsed.ok).toBe(false);
      expect(parsed.usage).toBe(USAGE);
    }
  });
});

describe('file routing CLI generate command', () => {
  test('generates routes with default options relative to cwd', async () => {
    await setupRoutes('default-app');
    const cwd = resolve(fixtureRoot, 'default-app');
    const io = captureIo(cwd);

    try {
      const code = await main(['routes', 'generate'], io);

      expect(code).toBe(0);
      expect(io.stdout.text).toContain('Generated file routes:');
      expect(io.stdout.text).toContain('- root: routes');
      expect(io.stdout.text).toContain('- output: .potentia/routes.generated.js');
      expect(io.stdout.text).toContain('- routes: 2');
      expect(io.stdout.text).toContain('- scopes: 0');
      expect(io.stderr.text).toBe('');

      const generated = await readFile(resolve(cwd, '.potentia/routes.generated.js'), 'utf8');
      expect(generated).toStartWith('// Generated by PotentiaJS. Do not edit by hand.');
      expect(generated).toContain("import { createRoutes, mount } from '@potentiajs/core';");
      expect(generated).not.toContain('node:fs');
    } finally {
      await cleanup();
    }
  });

  test('supports --cwd, --root, --out, and --package override', async () => {
    await setupRoutes('custom-app', 'app-routes');
    const cwd = resolve(fixtureRoot, 'custom-app');
    const io = captureIo('/tmp/ignored-cwd');

    try {
      const code = await main([
        'routes',
        'generate',
        '--cwd',
        cwd,
        '--root',
        'app-routes',
        '--out',
        'generated/routes.js',
        '--package',
        '@example/core'
      ], io);

      expect(code).toBe(0);
      expect(io.stdout.text).toContain('- root: app-routes');
      expect(io.stdout.text).toContain('- output: generated/routes.js');

      const generated = await readFile(resolve(cwd, 'generated/routes.js'), 'utf8');
      expect(generated).toContain("import { createRoutes, mount } from '@example/core';");
      expect(generated).not.toContain("import { createRoutes, mount } from '@potentiajs/core';");
    } finally {
      await cleanup();
    }
  });

  test('returns code 1 and safe diagnostics for generation failure', async () => {
    await cleanup();
    await mkdir(resolve(fixtureRoot, 'failure-app'), { recursive: true });
    const cwd = resolve(fixtureRoot, 'failure-app');
    const io = captureIo(cwd);

    try {
      const code = await main(['routes', 'generate'], io);

      expect(code).toBe(1);
      expect(io.stdout.text).toBe('');
      expect(io.stderr.text).toContain('File route generation failed:');
      expect(io.stderr.text).toContain('POTENTIA_FILE_ROUTE_MISSING_ROOT');
      expect(io.stderr.text).not.toContain(' at ');
    } finally {
      await cleanup();
    }
  });

  test('returns code 2 and usage for invalid usage', async () => {
    const io = captureIo(fixtureRoot);

    const code = await main(['routes', 'generate', '--watch'], io);

    expect(code).toBe(2);
    expect(io.stdout.text).toBe('');
    expect(io.stderr.text).toContain(USAGE);
    expect(io.stderr.text).toContain('Usage error: unknown option: --watch');
  });
});

describe('file routing CLI check command', () => {
  test('returns code 1 when output is missing and does not write output', async () => {
    await setupRoutes('missing-app');
    const cwd = resolve(fixtureRoot, 'missing-app');
    const io = captureIo(cwd);

    try {
      const code = await main(['routes', 'check'], io);

      expect(code).toBe(1);
      expect(io.stdout.text).toBe('');
      expect(io.stderr.text).toContain('File routes are not generated:');
      expect(io.stderr.text).toContain('- output: .potentia/routes.generated.js');
      expect(io.stderr.text).toContain('- run: potentia routes generate');
      expect(existsSync(resolve(cwd, '.potentia/routes.generated.js'))).toBe(false);
      expect(existsSync(resolve(cwd, '.potentia'))).toBe(false);
    } finally {
      await cleanup();
    }
  });

  test('returns code 0 when generated output is current', async () => {
    await setupRoutes('current-app');
    const cwd = resolve(fixtureRoot, 'current-app');

    try {
      expect(await main(['routes', 'generate'], captureIo(cwd))).toBe(0);
      const io = captureIo(cwd);
      const code = await main(['routes', 'check'], io);

      expect(code).toBe(0);
      expect(io.stdout.text).toContain('File routes are current:');
      expect(io.stdout.text).toContain('- root: routes');
      expect(io.stdout.text).toContain('- output: .potentia/routes.generated.js');
      expect(io.stdout.text).toContain('- routes: 2');
      expect(io.stdout.text).toContain('- scopes: 0');
      expect(io.stderr.text).toBe('');
    } finally {
      await cleanup();
    }
  });

  test('returns code 1 when generated output is stale and does not rewrite it', async () => {
    await setupRoutes('stale-app');
    const cwd = resolve(fixtureRoot, 'stale-app');
    const output = resolve(cwd, '.potentia/routes.generated.js');

    try {
      expect(await main(['routes', 'generate'], captureIo(cwd))).toBe(0);
      await writeFile(output, '// stale\n');
      const io = captureIo(cwd);
      const code = await main(['routes', 'check'], io);

      expect(code).toBe(1);
      expect(io.stdout.text).toBe('');
      expect(io.stderr.text).toContain('File routes are stale:');
      expect(io.stderr.text).toContain('- run: potentia routes generate');
      expect(await readFile(output, 'utf8')).toBe('// stale\n');
    } finally {
      await cleanup();
    }
  });

  test('returns code 1 and diagnostics when route generation fails', async () => {
    await cleanup();
    await mkdir(resolve(fixtureRoot, 'diagnostic-app'), { recursive: true });
    const cwd = resolve(fixtureRoot, 'diagnostic-app');
    const io = captureIo(cwd);

    try {
      const code = await main(['routes', 'check'], io);

      expect(code).toBe(1);
      expect(io.stdout.text).toBe('');
      expect(io.stderr.text).toContain('File route generation failed:');
      expect(io.stderr.text).toContain('POTENTIA_FILE_ROUTE_MISSING_ROOT');
      expect(io.stderr.text).not.toContain(' at ');
    } finally {
      await cleanup();
    }
  });

  test('returns code 2 and usage for invalid check usage', async () => {
    const io = captureIo(fixtureRoot);

    const code = await main(['routes', 'check', '--watch'], io);

    expect(code).toBe(2);
    expect(io.stdout.text).toBe('');
    expect(io.stderr.text).toContain(USAGE);
    expect(io.stderr.text).toContain('Usage error: unknown option: --watch');
  });

  test('uses normalized newline comparison', async () => {
    await setupRoutes('newline-app');
    const cwd = resolve(fixtureRoot, 'newline-app');
    const output = resolve(cwd, '.potentia/routes.generated.js');

    try {
      expect(await main(['routes', 'generate'], captureIo(cwd))).toBe(0);
      const generated = await readFile(output, 'utf8');
      await writeFile(output, generated.replace(/\n/g, '\r\n'));
      const io = captureIo(cwd);
      const code = await main(['routes', 'check'], io);

      expect(code).toBe(0);
      expect(io.stdout.text).toContain('File routes are current:');
      expect((await readFile(output, 'utf8')).includes('\r\n')).toBe(true);
    } finally {
      await cleanup();
    }
  });

  test('respects --cwd, --root, --out, and --package', async () => {
    await setupRoutes('check-custom-app', 'app-routes');
    const cwd = resolve(fixtureRoot, 'check-custom-app');

    try {
      expect(await main([
        'routes',
        'generate',
        '--cwd',
        cwd,
        '--root',
        'app-routes',
        '--out',
        'generated/routes.js',
        '--package',
        '@example/core'
      ], captureIo('/tmp/ignored-cwd'))).toBe(0);

      const io = captureIo('/tmp/ignored-cwd');
      const code = await main([
        'routes',
        'check',
        '--cwd',
        cwd,
        '--root',
        'app-routes',
        '--out',
        'generated/routes.js',
        '--package',
        '@example/core'
      ], io);

      expect(code).toBe(0);
      expect(io.stdout.text).toContain('- root: app-routes');
      expect(io.stdout.text).toContain('- output: generated/routes.js');
    } finally {
      await cleanup();
    }
  });

  test('checkFileRoutes exposes status without writing', async () => {
    await setupRoutes('helper-app');
    const cwd = resolve(fixtureRoot, 'helper-app');

    try {
      const result = await checkFileRoutes({
        rootDir: 'routes',
        outputFile: '.potentia/routes.generated.js',
        packageName: '@potentiajs/core',
        cwd
      });

      expect(result.status).toBe('missing');
      expect(result.written).toBe(false);
      expect(existsSync(resolve(cwd, '.potentia/routes.generated.js'))).toBe(false);
    } finally {
      await cleanup();
    }
  });
});


describe('file routing CLI JSON output', () => {
  test('creates JSON envelopes with safe diagnostics', () => {
    expect(createJsonEnvelope({
      ok: true,
      command: 'routes generate',
      status: 'generated',
      root: 'routes',
      output: '.potentia/routes.generated.js',
      packageName: '@potentiajs/core',
      routes: 2,
      scopes: 0,
      diagnostics: [{ code: 'X', relativePath: 'routes/index.js', message: 'safe' }]
    })).toEqual({
      ok: true,
      command: 'routes generate',
      status: 'generated',
      root: 'routes',
      output: '.potentia/routes.generated.js',
      package: '@potentiajs/core',
      routes: 2,
      scopes: 0,
      diagnostics: [{ code: 'X', message: 'safe', path: 'routes/index.js' }]
    });

    expect(toJsonDiagnostics([{
      code: 'POTENTIA_FILE_ROUTE_READ_FAILED',
      outputFile: '/tmp/secret/routes.generated.js',
      message: 'Failed to read',
      cause: 'raw internal cause'
    }])).toEqual([{ code: 'POTENTIA_FILE_ROUTE_READ_FAILED', message: 'Failed to read' }]);
  });

  test('routes generate --json succeeds, writes output, and suppresses human text', async () => {
    await setupRoutes('json-generate-app');
    const cwd = resolve(fixtureRoot, 'json-generate-app');
    const io = captureIo(cwd);

    try {
      const code = await main(['routes', 'generate', '--json'], io);
      const json = JSON.parse(io.stdout.text);

      expect(code).toBe(0);
      expect(json).toEqual({
        ok: true,
        command: 'routes generate',
        status: 'generated',
        root: 'routes',
        output: '.potentia/routes.generated.js',
        package: '@potentiajs/core',
        routes: 2,
        scopes: 0,
        diagnostics: []
      });
      expect(io.stdout.text).not.toContain('Generated file routes:');
      expect(io.stderr.text).toBe('');
      expect(existsSync(resolve(cwd, '.potentia/routes.generated.js'))).toBe(true);
    } finally {
      await cleanup();
    }
  });

  test('routes generate --json failure returns failed JSON on stdout', async () => {
    await cleanup();
    await mkdir(resolve(fixtureRoot, 'json-generate-failure-app'), { recursive: true });
    const cwd = resolve(fixtureRoot, 'json-generate-failure-app');
    const io = captureIo(cwd);

    try {
      const code = await main(['routes', 'generate', '--json'], io);
      const json = JSON.parse(io.stdout.text);

      expect(code).toBe(1);
      expect(json.ok).toBe(false);
      expect(json.command).toBe('routes generate');
      expect(json.status).toBe('failed');
      expect(json.root).toBe('routes');
      expect(json.output).toBe('.potentia/routes.generated.js');
      expect(json.package).toBe('@potentiajs/core');
      expect(json.diagnostics[0].code).toBe('POTENTIA_FILE_ROUTE_MISSING_ROOT');
      expect(JSON.stringify(json)).not.toContain(' at ');
      expect(io.stderr.text).toBe('');
    } finally {
      await cleanup();
    }
  });

  test('routes check --json reports missing without writing output', async () => {
    await setupRoutes('json-missing-app');
    const cwd = resolve(fixtureRoot, 'json-missing-app');
    const io = captureIo(cwd);

    try {
      const code = await main(['routes', 'check', '--json'], io);
      const json = JSON.parse(io.stdout.text);

      expect(code).toBe(1);
      expect(json.status).toBe('missing');
      expect(json.ok).toBe(false);
      expect(json.hint).toBe('Run potentia routes generate');
      expect(json.routes).toBe(2);
      expect(json.scopes).toBe(0);
      expect(json.diagnostics).toEqual([]);
      expect(io.stderr.text).toBe('');
      expect(existsSync(resolve(cwd, '.potentia/routes.generated.js'))).toBe(false);
      expect(existsSync(resolve(cwd, '.potentia'))).toBe(false);
    } finally {
      await cleanup();
    }
  });

  test('routes check --json reports current with exit 0', async () => {
    await setupRoutes('json-current-app');
    const cwd = resolve(fixtureRoot, 'json-current-app');

    try {
      expect(await main(['routes', 'generate'], captureIo(cwd))).toBe(0);
      const io = captureIo(cwd);
      const code = await main(['routes', 'check', '--json'], io);
      const json = JSON.parse(io.stdout.text);

      expect(code).toBe(0);
      expect(json).toEqual({
        ok: true,
        command: 'routes check',
        status: 'current',
        root: 'routes',
        output: '.potentia/routes.generated.js',
        package: '@potentiajs/core',
        routes: 2,
        scopes: 0,
        diagnostics: []
      });
      expect(io.stderr.text).toBe('');
    } finally {
      await cleanup();
    }
  });

  test('routes check --json reports stale without rewriting output', async () => {
    await setupRoutes('json-stale-app');
    const cwd = resolve(fixtureRoot, 'json-stale-app');
    const output = resolve(cwd, '.potentia/routes.generated.js');

    try {
      expect(await main(['routes', 'generate'], captureIo(cwd))).toBe(0);
      await writeFile(output, '// stale\n');
      const io = captureIo(cwd);
      const code = await main(['routes', 'check', '--json'], io);
      const json = JSON.parse(io.stdout.text);

      expect(code).toBe(1);
      expect(json.status).toBe('stale');
      expect(json.ok).toBe(false);
      expect(json.hint).toBe('Run potentia routes generate');
      expect(io.stderr.text).toBe('');
      expect(await readFile(output, 'utf8')).toBe('// stale\n');
    } finally {
      await cleanup();
    }
  });

  test('routes check --json failure returns failed JSON on stdout', async () => {
    await cleanup();
    await mkdir(resolve(fixtureRoot, 'json-check-failure-app'), { recursive: true });
    const cwd = resolve(fixtureRoot, 'json-check-failure-app');
    const io = captureIo(cwd);

    try {
      const code = await main(['routes', 'check', '--json'], io);
      const json = JSON.parse(io.stdout.text);

      expect(code).toBe(1);
      expect(json.ok).toBe(false);
      expect(json.command).toBe('routes check');
      expect(json.status).toBe('failed');
      expect(json.diagnostics[0].code).toBe('POTENTIA_FILE_ROUTE_MISSING_ROOT');
      expect(JSON.stringify(json)).not.toContain(' at ');
      expect(io.stderr.text).toBe('');
    } finally {
      await cleanup();
    }
  });

  test('invalid usage with --json emits invalid-usage JSON on stdout', async () => {
    const io = captureIo(fixtureRoot);

    const code = await main(['routes', 'watch', '--json'], io);
    const json = JSON.parse(io.stdout.text);

    expect(code).toBe(2);
    expect(json).toEqual({
      ok: false,
      command: null,
      status: 'invalid-usage',
      diagnostics: [{
        code: 'POTENTIA_CLI_INVALID_USAGE',
        message: USAGE
      }]
    });
    expect(io.stderr.text).toBe('');
    expect(JSON.stringify(json)).not.toContain(' at ');
  });

  test('invalid usage with resolved command and --json keeps best-effort command', async () => {
    const io = captureIo(fixtureRoot);

    const code = await main(['routes', 'check', '--watch', '--json'], io);
    const json = JSON.parse(io.stdout.text);

    expect(code).toBe(2);
    expect(json.command).toBe('routes check');
    expect(json.status).toBe('invalid-usage');
    expect(json.diagnostics).toHaveLength(1);
    expect(io.stderr.text).toBe('');
  });
});

describe('file routing CLI package expectations', () => {
  test('package exposes potentia bin without root API pollution', () => {
    expect(packageJson.bin).toEqual({ potentia: './bin/potentia.js' });
    expect(existsSync(new URL('../bin/potentia.js', import.meta.url))).toBe(true);
    expect('main' in rootApi).toBe(false);
    expect('parseArgs' in rootApi).toBe(false);
    expect('checkFileRoutes' in rootApi).toBe(false);
    expect('generateFileRoutes' in rootApi).toBe(false);
    expect(Object.keys(fileRoutingApi).sort()).toEqual(['generateFileRoutes']);
  });
});

async function setupRoutes(name, routesDir = 'routes') {
  await cleanup();
  const root = resolve(fixtureRoot, name, routesDir);
  await mkdir(resolve(root, 'users'), { recursive: true });
  await writeFile(resolve(root, 'index.js'), [
    "import { ok, route, text } from '@potentiajs/core';",
    "export default route('GET', '/', () => ok(text('home')));",
    ''
  ].join('\n'));
  await writeFile(resolve(root, 'users/[id].js'), [
    "import { json, ok, route } from '@potentiajs/core';",
    "export default route('GET', '/:id', (ctx) => ok(json({ id: ctx.params.id })));",
    ''
  ].join('\n'));
}

async function cleanup() {
  await rm(fixtureRoot, { recursive: true, force: true });
}

function captureIo(cwd) {
  return {
    cwd,
    stdout: captureStream(),
    stderr: captureStream()
  };
}

function captureStream() {
  return {
    text: '',
    write(chunk) {
      this.text += String(chunk);
    }
  };
}

