import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

import { describe, expect, test } from 'bun:test';

import { generateFileRoutes } from '../src/file-routing.js';

const fixtureRoot = new URL('./fixtures/file-routing-public-api/', import.meta.url).pathname;
const routesRoot = resolve(fixtureRoot, 'routes');
const outputFile = resolve(fixtureRoot, '.potentia/routes.generated.js');
const sideEffectFile = resolve(fixtureRoot, 'executed.txt');

describe('file routing public API wrapper', () => {
  test('generates deterministic explicit route module with public defaults', async () => {
    await setupRoutes();

    try {
      const first = await generateFileRoutes({ rootDir: routesRoot, outputFile });
      const second = await generateFileRoutes({ rootDir: routesRoot, outputFile });

      expect(first.ok).toBe(true);
      expect(second.ok).toBe(true);
      expect(first.source).toBe(second.source);
      expect(first.written).toBe(true);
      expect(first.routes).toBe(2);
      expect(first.scopes).toBe(0);
      expect(first.errors).toEqual([]);
      expect(first.diagnostics).toEqual([]);
      expect(first.source).toStartWith('// Generated by PotentiaJS. Do not edit by hand.');
      expect(first.source).toContain("import { createRoutes, mount } from '@potentiajs/core';");
      expect(first.source).toContain('export default createRoutes({');
      expect(first.source).not.toContain('node:fs');
      expect(await readFile(outputFile, 'utf8')).toBe(first.source);
    } finally {
      await cleanup();
    }
  });

  test('preserves packageName override', async () => {
    await setupRoutes();

    try {
      const result = await generateFileRoutes({
        rootDir: routesRoot,
        outputFile,
        packageName: '@example/local-core'
      });

      expect(result.ok).toBe(true);
      expect(result.source).toContain("import { createRoutes, mount } from '@example/local-core';");
      expect(result.source).not.toContain("import { createRoutes, mount } from '@potentiajs/core';");
    } finally {
      await cleanup();
    }
  });

  test('returns deterministic diagnostics and preserves previous output on failure', async () => {
    await setupRoutes();
    await mkdir(dirname(outputFile), { recursive: true });
    await writeFile(outputFile, 'previous valid output');

    try {
      const result = await generateFileRoutes({
        rootDir: resolve(fixtureRoot, 'missing-routes'),
        outputFile
      });

      expect(result.ok).toBe(false);
      expect(result.written).toBe(false);
      expect(result.source).toBe('');
      expect(result.diagnostics).toEqual(result.errors);
      expect(result.errors).toEqual([expect.objectContaining({
        code: 'POTENTIA_FILE_ROUTE_MISSING_ROOT',
        message: 'Route root directory was not found'
      })]);
      expect(await readFile(outputFile, 'utf8')).toBe('previous valid output');
    } finally {
      await cleanup();
    }
  });

  test('does not execute route modules during generation', async () => {
    await setupRoutes();

    try {
      const result = await generateFileRoutes({ rootDir: routesRoot, outputFile });

      expect(result.ok).toBe(true);
      await expect(readFile(sideEffectFile, 'utf8')).rejects.toThrow();
    } finally {
      await cleanup();
    }
  });
});

async function setupRoutes() {
  await cleanup();
  await mkdir(resolve(routesRoot, 'users'), { recursive: true });
  await writeFile(resolve(routesRoot, 'index.js'), [
    "import { route, text, ok } from '@potentiajs/core';",
    `import { writeFileSync } from 'node:fs';`,
    `writeFileSync(${JSON.stringify(sideEffectFile)}, 'executed');`,
    "export default route('GET', '/', () => ok(text('home')));",
    ''
  ].join('\n'));
  await writeFile(resolve(routesRoot, 'users/[id].js'), [
    "import { route, json, ok } from '@potentiajs/core';",
    "export default route('GET', '/:id', (ctx) => ok(json({ id: ctx.params.id })));",
    ''
  ].join('\n'));
}

async function cleanup() {
  await rm(fixtureRoot, { recursive: true, force: true });
}
