import { readFile, rm } from 'node:fs/promises';

import { describe, expect, test } from 'bun:test';

const exampleRoot = new URL('../examples/full-flow-basic/', import.meta.url);
const generatedDir = new URL('./.potentia/', exampleRoot);
const generatedFile = new URL('./.potentia/routes.generated.js', exampleRoot);

describe('full-flow basic example', () => {
  test('generates routes and serves form/action flow', async () => {
    await cleanup();

    try {
      const { generate } = await import(`../examples/full-flow-basic/generate.js?cache=${Date.now()}`);
      const result = await generate();

      expect(result.ok).toBe(true);
      expect(result.routes).toBe(4);
      expect(result.scopes).toBe(1);
      expect(result.diagnostics).toEqual([]);

      const source = await readFile(generatedFile, 'utf8');
      expect(source).toStartWith('// Generated by PotentiaJS. Do not edit by hand.');
      expect(source).toContain("import { createRoutes, mount } from '@potentiajs/core';");
      expect(source).toContain("import route0 from '../routes/index.js';");
      expect(source).toContain("import route1 from '../routes/users/index.js';");
      expect(source).toContain("import route3 from '../routes/users/new.js';");
      expect(source).not.toContain('node:fs');

      const { app } = await import(`../examples/full-flow-basic/app.js?cache=${Date.now()}`);

      const home = await app.fetch(new Request('http://localhost/'));
      expect(home.status).toBe(200);
      const homeHtml = await home.text();
      expect(homeHtml).toContain('Potentia full-flow example');
      expect(homeHtml).toContain('/users/new');

      const form = await app.fetch(new Request('http://localhost/users/new'));
      expect(form.status).toBe(200);
      expect(form.headers.get('content-type')).toContain('text/html');
      const formHtml = await form.text();
      expect(formHtml).toContain('<form method="POST" action="/users"');
      expect(formHtml).toContain('name="email" type="email"');
      expect(formHtml).toContain('name="password" type="password"');
      expect(formHtml).not.toContain('node:fs');

      const invalid = await post(app, '/users', 'name=&email=bad&password=secret-value');
      expect(invalid.status).toBe(400);
      const invalidHtml = await invalid.text();
      expect(invalidHtml).toContain('Name is required.');
      expect(invalidHtml).toContain('Email must include @.');
      expect(invalidHtml).toContain('value="bad"');
      expect(invalidHtml).not.toContain('secret-value');
      expect(invalidHtml).toContain('data-potentia-errors-for="email"');

      const domainFailure = await post(app, '/users', 'name=Ada&email=taken%40example.com&password=secret-value');
      expect(domainFailure.status).toBe(409);
      const domainHtml = await domainFailure.text();
      expect(domainHtml).toContain('Email is already in use.');
      expect(domainHtml).toContain('data-potentia-form-errors');
      expect(domainHtml).toContain('value="Ada"');
      expect(domainHtml).toContain('value="taken@example.com"');
      expect(domainHtml).not.toContain('secret-value');

      const success = await post(app, '/users', 'name=Ada&email=ada%40example.com&password=secret-value');
      expect(success.status).toBe(303);
      expect(success.headers.get('location')).toBe('/users/ada');

      const user = await app.fetch(new Request('http://localhost/users/ada'));
      expect(user.status).toBe(200);
      expect(await user.text()).toContain('User ada');
    } finally {
      await cleanup();
    }
  });
});

function post(app, path, body) {
  return app.fetch(new Request(`http://localhost${path}`, {
    method: 'POST',
    headers: { 'content-type': 'application/x-www-form-urlencoded' },
    body: body
  }));
}

async function cleanup() {
  await rm(generatedDir, { recursive: true, force: true });
}
